version: '3.9'

services:
  angular-dev:
    build: .
    container_name: angular-dev-container
    ports:
      - "4200:4200"
    volumes:
      - .:/app            # live reload
      - /app/node_modules # Ã©viter conflit host/container
    command: npm run start -- --host 0.0.0.0
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env

  